//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EventMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EventMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("RegisterEvent", RegisterEvent);
		L.RegFunction("UnRegisterEvent", UnRegisterEvent);
		L.RegFunction("DispatchEvent", DispatchEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegFunction("EventHandler", EventMgr_EventHandler);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			EventMgr obj = (EventMgr)ToLua.CheckObject<EventMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			EventMgr.EventHandler arg1 = (EventMgr.EventHandler)ToLua.CheckDelegate<EventMgr.EventHandler>(L, 3);
			obj.RegisterEvent(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegisterEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			EventMgr obj = (EventMgr)ToLua.CheckObject<EventMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			EventMgr.EventHandler arg1 = (EventMgr.EventHandler)ToLua.CheckDelegate<EventMgr.EventHandler>(L, 3);
			obj.UnRegisterEvent(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DispatchEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			EventMgr obj = (EventMgr)ToLua.CheckObject<EventMgr>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.CheckObjectArray(L, 3);
			obj.DispatchEvent(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EventMgr_EventHandler(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<EventMgr.EventHandler>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<EventMgr.EventHandler>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

