//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetWorkMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NetWorkMgr), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("CreateRandomName", CreateRandomName);
		L.RegFunction("TryGetLastMessage", TryGetLastMessage);
		L.RegFunction("TryGetLastFriendMessage", TryGetLastFriendMessage);
		L.RegFunction("GetFriendMsgCount", GetFriendMsgCount);
		L.RegFunction("AddFriendMessage", AddFriendMessage);
		L.RegFunction("EH_onRecieveMeMessage", EH_onRecieveMeMessage);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("globalData", get_globalData, set_globalData);
		L.RegVar("eventMgr", get_eventMgr, set_eventMgr);
		L.RegVar("gameMgr", get_gameMgr, set_gameMgr);
		L.RegVar("me", get_me, set_me);
		L.RegVar("friends", get_friends, set_friends);
		L.RegVar("worldMsg", get_worldMsg, set_worldMsg);
		L.RegVar("friendMsg", get_friendMsg, set_friendMsg);
		L.RegVar("friendToTalk", get_friendToTalk, set_friendToTalk);
		L.RegVar("friendTalkMsgs", get_friendTalkMsgs, set_friendTalkMsgs);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreateRandomName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			string o = obj.CreateRandomName();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TryGetLastMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			System.Collections.Generic.List<NetWorkMgr.Message> o = obj.TryGetLastMessage(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TryGetLastFriendMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			System.Collections.Generic.List<NetWorkMgr.Message> o = obj.TryGetLastFriendMessage(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFriendMsgCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			NetWorkMgr.Player arg0 = (NetWorkMgr.Player)ToLua.CheckObject<NetWorkMgr.Player>(L, 2);
			int o = obj.GetFriendMsgCount(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddFriendMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			NetWorkMgr.Message arg0 = (NetWorkMgr.Message)ToLua.CheckObject<NetWorkMgr.Message>(L, 2);
			obj.AddFriendMessage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EH_onRecieveMeMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			NetWorkMgr obj = (NetWorkMgr)ToLua.CheckObject<NetWorkMgr>(L, 1);
			object[] arg0 = ToLua.CheckObjectArray(L, 2);
			obj.EH_onRecieveMeMessage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_globalData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			GlobalData ret = obj.globalData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index globalData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eventMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			EventMgr ret = obj.eventMgr;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_gameMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			GameMgr ret = obj.gameMgr;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gameMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_me(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			NetWorkMgr.Player ret = obj.me;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index me on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_friends(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Player> ret = obj.friends;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friends on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_worldMsg(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Message> ret = obj.worldMsg;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index worldMsg on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_friendMsg(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Message> ret = obj.friendMsg;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendMsg on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_friendToTalk(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			NetWorkMgr.Player ret = obj.friendToTalk;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendToTalk on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_friendTalkMsgs(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.Dictionary<NetWorkMgr.Player,System.Collections.Generic.List<NetWorkMgr.Message>> ret = obj.friendTalkMsgs;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendTalkMsgs on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_globalData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			GlobalData arg0 = (GlobalData)ToLua.CheckObject<GlobalData>(L, 2);
			obj.globalData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index globalData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eventMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			EventMgr arg0 = (EventMgr)ToLua.CheckObject<EventMgr>(L, 2);
			obj.eventMgr = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_gameMgr(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			GameMgr arg0 = (GameMgr)ToLua.CheckObject<GameMgr>(L, 2);
			obj.gameMgr = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gameMgr on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_me(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			NetWorkMgr.Player arg0 = (NetWorkMgr.Player)ToLua.CheckObject<NetWorkMgr.Player>(L, 2);
			obj.me = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index me on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_friends(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Player> arg0 = (System.Collections.Generic.List<NetWorkMgr.Player>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<NetWorkMgr.Player>));
			obj.friends = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friends on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_worldMsg(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Message> arg0 = (System.Collections.Generic.List<NetWorkMgr.Message>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<NetWorkMgr.Message>));
			obj.worldMsg = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index worldMsg on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_friendMsg(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.List<NetWorkMgr.Message> arg0 = (System.Collections.Generic.List<NetWorkMgr.Message>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<NetWorkMgr.Message>));
			obj.friendMsg = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendMsg on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_friendToTalk(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			NetWorkMgr.Player arg0 = (NetWorkMgr.Player)ToLua.CheckObject<NetWorkMgr.Player>(L, 2);
			obj.friendToTalk = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendToTalk on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_friendTalkMsgs(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr obj = (NetWorkMgr)o;
			System.Collections.Generic.Dictionary<NetWorkMgr.Player,System.Collections.Generic.List<NetWorkMgr.Message>> arg0 = (System.Collections.Generic.Dictionary<NetWorkMgr.Player,System.Collections.Generic.List<NetWorkMgr.Message>>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<NetWorkMgr.Player,System.Collections.Generic.List<NetWorkMgr.Message>>));
			obj.friendTalkMsgs = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index friendTalkMsgs on a nil value");
		}
	}
}

