//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NetWorkMgr_PlayerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NetWorkMgr.Player), typeof(System.Object));
		L.RegFunction("New", _CreateNetWorkMgr_Player);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("name", get_name, set_name);
		L.RegVar("gender", get_gender, set_gender);
		L.RegVar("state", get_state, set_state);
		L.RegVar("playingTimeInSec", get_playingTimeInSec, set_playingTimeInSec);
		L.RegVar("portrait", get_portrait, set_portrait);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateNetWorkMgr_Player(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				string arg0 = ToLua.CheckString(L, 1);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
				NetWorkMgr.PlayerState arg2 = (NetWorkMgr.PlayerState)ToLua.CheckObject(L, 3, typeof(NetWorkMgr.PlayerState));
				float arg3 = (float)LuaDLL.luaL_checknumber(L, 4);
				NetWorkMgr.Player obj = new NetWorkMgr.Player(arg0, arg1, arg2, arg3);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: NetWorkMgr.Player.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_gender(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			bool ret = obj.gender;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gender on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_state(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			NetWorkMgr.PlayerState ret = obj.state;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index state on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_playingTimeInSec(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			float ret = obj.playingTimeInSec;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index playingTimeInSec on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_portrait(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			int ret = obj.portrait;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index portrait on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_gender(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.gender = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index gender on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_state(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			NetWorkMgr.PlayerState arg0 = (NetWorkMgr.PlayerState)ToLua.CheckObject(L, 2, typeof(NetWorkMgr.PlayerState));
			obj.state = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index state on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_playingTimeInSec(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.playingTimeInSec = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index playingTimeInSec on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_portrait(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NetWorkMgr.Player obj = (NetWorkMgr.Player)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.portrait = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index portrait on a nil value");
		}
	}
}

